defaults: &defaults
  adapter:  postgresql
  pool:     5
  timeout:  5000
  encoding: utf8

development:
  <<:       *defaults
  username: marius
  password:
  database: wts_dev
  host:     localhost

test:
  <<:       *defaults
  username: postgres
  password:
  database: wts_test
  host:     localhost

production:
  <<:       *defaults
  username: <%=ENV['OPENSHIFT_POSTGRESQL_DB_USERNAME']%>
  password: <%=ENV['OPENSHIFT_POSTGRESQL_DB_PASSWORD']%>
  database: <%=ENV['OPENSHIFT_APP_NAME']%>
  host:     <%=ENV['OPENSHIFT_POSTGRESQL_DB_HOST']%>
  port:     <%=ENV['OPENSHIFT_POSTGRESQL_DB_PORT']%>
